// export const sample_foods = [
//   {
//     id: '1',
//     name: 'Pizza Pepperoni',
//     cookTime: '10-20',
//     price: 10,
//     favorite: false,
//     origins: ['italy'],
//     stars: 4.5,
//     imageUrl: 'https://img.freepik.com/free-photo/plate-biryani-with-bunch-food-it_505751-3819.jpg',
//     tags: ['FastFood', 'Pizza', 'Lunch'],
//   },
//   {
//     id: '2',
//     name: 'Meatball',
//     price: 20,
//     cookTime: '20-30',
//     favorite: true,
//     origins: ['persia', 'middle east', 'china'],
//     stars: 5,
//     imageUrl: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8emluZ2VyJTIwYnVyZ2VyfGVufDB8fDB8fHww&w=1000&q=80',
//     tags: ['SlowFood', 'Lunch'],
//   },
//   {
//     id: '3',
//     name: 'Hamburger',
//     price: 5,
//     cookTime: '10-15',
//     favorite: false,
//     origins: ['germany', 'us'],
//     stars: 3.5,
//     imageUrl: 'https://img.freepik.com/premium-photo/chicken-shashlik-chicken-manchurian-with-salad-fried-rice-served-dish-isolated-grey-background-side-view-indian-pakistani-food_689047-3033.jpg?w=2000',
//     tags: ['FastFood', 'Hamburger'],
//   },
//   {
//     id: '4',
//     name: 'Fried Potatoes',
//     price: 2,
//     cookTime: '15-20',
//     favorite: true,
//     origins: ['belgium', 'france'],
//     stars: 3,
//     imageUrl: 'https://media.istockphoto.com/id/1389015478/photo/nihari-with-naan.jpg?s=612x612&w=0&k=20&c=YBmZlHo-cZxJ1FOsEwR0PR5SWNTKWbhw6VsOWi0REoM=',
//     tags: ['FastFood', 'Fry'],
//   },
//   {
//     id: '5',
//     name: 'Chicken Soup',
//     price: 11,
//     cookTime: '40-50',
//     favorite: false,
//     origins: ['india', 'asia'],
//     stars: 3.5,
//     imageUrl: 'https://img.freepik.com/free-photo/crispy-fried-chicken-plate-with-salad-carrot_1150-20212.jpg?w=2000",
//     description: "Crispy Broast, Bun & Fries',
//     tags: ['SlowFood', 'Soup'],
//   },
//   {
//     id: '6',
//     name: 'Vegetables Pizza',
//     price: 9,
//     cookTime: '40-50',
//     favorite: false,
//     origins: ['italy'],
//     stars: 4.0,
//     imageUrl: 'https://media.istockphoto.com/id/967274038/photo/homemade-chicken-tikka-masala.webp?b=1&s=170667a&w=0&k=20&c=8eSCPcx7Hx3ckeHtSlaCHW8rx2mRntHz5lXGx9-XZHU=',
//     tags: ['FastFood', 'Pizza', 'Lunch'],
//   },
// ];

// export const sample_tags = [
//   { name: 'All', count: 6 },
//   { name: 'FastFood', count: 4 },
//   { name: 'Pizza', count: 2 },
//   { name: 'Lunch', count: 3 },
//   { name: 'SlowFood', count: 2 },
//   { name: 'Hamburger', count: 1 },
//   { name: 'Fry', count: 1 },
//   { name: 'Soup', count: 1 },
// ];

// export const sample_users = [
//   {
//     id: 1,
//     name: 'John Doe',
//     email: 'john@gmail.com',
//     password: '12345',
//     address: 'Toronto On',
//     isAdmin: false,
//   },
//   {
//     id: 2,
//     name: 'Jane Doe',
//     email: 'jane@gmail.com',
//     password: '12345',
//     address: 'Shanghai',
//     isAdmin: true,
//   },
// ];
